spring:
  datasource:
    url: ${EXAM_PROD_DB_URL}
    username: ${EXAM_PROD_DB_USERNAME}
    password: ${EXAM_PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # ✅ Production safety — does not auto-modify schema
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: prod

# Optional logging
logging:
  level:
    org.springframework: WARN
